///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/FrisBot.aks
/// Generation time: jue jun  7 00:09:38 CEST 2018
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x47
#define song_ingame_size     3583
#define song_ingame_end      0xE46

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
